[platformio]
src_dir = src

[env]
framework = arduino
build_src_flags = 

[env:PicoSound-Tiny]
extra_scripts = pre:copy_firmware.py
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
board_build.core = earlephilhower
build_flags = -DAPP_VERSION=0.4
lib_deps =
    WS281xProcessor      @1.0.1
    MobaLedLib           =https://github.com/Hardi-St/MobaLedLib#longInpAddresses
    PicoFlashStorage     @=1.2.0
    MLLSoundTiny         @=1.0.0
    SoftwareSerialTx     @=0.1.0
    bxparks/AceButton    @=1.9.2