[platformio]
src_dir = src

[env]
framework = arduino
build_src_flags = 

[env:picoSoundTiny]
extra_scripts = post:copy_firmware.py
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
Board = pico
framework = arduino
board_build.core = earlephilhower

lib_deps =
    WS281xProcessor=https://github.com/Jueff/WS281xProcessor.git
    MobaLedLib=      https://github.com/Hardi-St/MobaLedLib#longInpAddresses
    PicoFlashStorage=https://github.com/Jueff/PicoFlashStorage.git#v1.0.0
    SoftwareSerialTx@=0.1.0