[platformio]
src_dir = .
    
[env]
framework = arduino
build_src_flags = 

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
Board = pico
framework = arduino
board_build.core = earlephilhower
build_flags =
lib_deps =
    WS281xProcessor=file://../../../../Arduino/libraries/WS281xProcessor @ 0.1
    MobaLedLib=     file://../../../../Arduino/libraries/MobaLedLib
